### ISSUE TITLE
[Todo] Backend Todo List

### ISSUE THREAD

**Issue by Shaa-code** [codestates-seb/seb39_main_014#8]
### 인증 및 권한

- [ ] 회원가입 구현 #7 
- [ ] 로그인 구현
- [ ] 회원 탈퇴
- [ ] 소셜 로그인 ( OAuth 2.0 ) 구현

### 조회기능

- [ ] 랜딩페이지 ( 저번 달 매치된 모임수 구현 )
- [ ] 인기 기술 스택 조회
- [ ] 전체 게시글 조회
- [ ] 스터디 게시글 조회
- [ ] 프로젝트 게시글 조회
- [ ] 특정 게시글 조회

### 게시글 기능

- [ ] 게시글 작성
- [ ] 게시글 수정
- [ ] 게시글 삭제

### 댓글 기능

- [ ] 댓글 작성
- [ ] 댓글 수정
- [ ] 댓글 삭제

### 북마크 기능

- [ ] 게시글 북마크 하기
- [ ] 게시글 북마크 취소(전체게시글, 마이페이지)

### 신청/수락 기능

- [ ] 스터디 / 프로젝트 신청
- [ ] 스터디 / 프로젝트 신청 수락

### 마이페이지 기능

- [ ] 회원 정보 Info 수정
- [ ] 북마크한 게시글 확인
